### ISSUE TITLE
Syntax error at line 46

### ISSUE THREAD

**Issue by ffurano** [razeh/sketchucam-gcode-optimizer#1]
Hi,

 having found the same gcode issues that you describe, I tried using your script, and it blocks with a syntax error at line 46. Cold it be that an incomplete version has been pushed ?

$ python3 optimizer.py dent.nc 
  File "optimizer.py", line 46
    "G0".
        ^
SyntaxError: invalid syntax

Thanks for having a look
Fabrizio

**Comment by razeh** [comment]
Give it a go now --- it was just a comment that required fixing.

**Comment by ffurano** [comment]
That syntax error is fixed now, thanks. The script does not work yet, though.

To me it does something only with Python 3.5 (which version are you using ?), and I have to fix a print statement.

Fixed the print into print(...), it blocks with the following error:

Traceback (most recent call last):
  File "./optimizer.py", line 244, in <module>
    main()
  File "./optimizer.py", line 237, in main
    commands = readFile(sys.argv[1])
  File "./optimizer.py", line 233, in readFile
    commands += factory.generate(line, text.rstrip())
  File "./optimizer.py", line 225, in generate
    return self.generate_from_tokens(line_number, line, tokens)
  File "./optimizer.py", line 217, in generate_from_tokens
    return [self.last_command(line_number, line)]
TypeError: 'NoneType' object is not callable

**Comment by razeh** [comment]
I'm using python 2.7

**Comment by siredmar** [comment]
I got the same problem with the log provided by ffurano:


Traceback (most recent call last):
File "./optimizer.py", line 244, in 
main()
File "./optimizer.py", line 237, in main
commands = readFile(sys.argv[1])
File "./optimizer.py", line 233, in readFile
commands += factory.generate(line, text.rstrip())
File "./optimizer.py", line 225, in generate
return self.generate_from_tokens(line_number, line, tokens)
File "./optimizer.py", line 217, in generate_from_tokens
return [self.last_command(line_number, line)]
TypeError: 'NoneType' object is not callable

I am using Linux and tried using Python 2.7.12 and Python 3.6.1
